DROP TABLE IF EXISTS gym_clients;
DROP TABLE IF EXISTS gym_classes;
DROP TABLE IF EXISTS gym_visits;

CREATE TABLE IF NOT EXISTS gym_clients (
    client_id UUID PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    membership_type VARCHAR(50) CHECK (membership_type IN ('Basic', 'Standard', 'Premium')),
    join_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS gym_classes (
    class_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR(100) NOT NULL,
    trainer_name VARCHAR(100) NOT NULL,
    class_category VARCHAR(50) NOT NULL CHECK (class_category IN ('Category1', 'Category2', 'Category3', 'Category4', 'Category5')),
    
);

CREATE TABLE IF NOT EXISTS gym_visits (
    visit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date TIMESTAMP NOT NULL,
    client_id UUID,
    class_id INTEGER,
    FOREIGN KEY (client_id) REFERENCES gym_clients(client_id),
    FOREIGN KEY (class_id) REFERENCES gym_classes(class_id)
);

EXPLAIN ANALYZE
SELECT
    gc.full_name,
    (SELECT COUNT(*)
     FROM gym_visits gv
     JOIN gym_classes gcl ON gv.class_id = gcl.class_id
     where gv.client_id = gc.client_id
     and gcl.class_category = 'Category2'
     and gcl.trainer_name in (
         select trainer_name
         from gym_classes
         group by trainer_name
         having COUNT(*) > 1
     )) as visits_count
from gym_clients gc
join gym_visits gv2 on gc.client_id = gv2.client_id
where gc.membership_type = 'Premium'
and gc.client_id in (
    select client_id
    from gym_visits
    where visit_date > (select MIN(visit_date) from gym_visits)
);

CREATE INDEX IF NOT EXISTS idx_gym_visits_client_id
    ON gym_visits(client_id);

CREATE INDEX IF NOT EXISTS idx_gym_visits_class_id
    ON gym_visits(class_id);

CREATE INDEX IF NOT EXISTS idx_gym_classes_category
    ON gym_classes(class_category);

CREATE INDEX IF NOT EXISTS idx_gym_clients_membership_type
    ON gym_clients(membership_type);

EXPLAIN ANALYZE
with popular_trainers as (
   select trainer_name
   from gym_classes
   group by trainer_name
   having COUNT(*) > 1
),

filtered_visits as (
    select gv.client_id,
           COUNT(*) as num_of_visits
    from gym_visits gv
    join gym_classes gcl on gv.class_id = gcl.class_id
    where gcl.class_category = 'Category2'
    and gcl.trainer_name in (
         select trainer_name
         from popular_trainers
    )
    group by gv.client_id
),

active_clients as (
   select distinct client_id
   from gym_visits
   where visit_date > (select MIN(visit_date) from gym_visits)
)

select
    gc.full_name,
    coalesce(fv.num_of_visits, 0) as visits_count
from gym_clients gc
inner join active_clients ac on gc.client_id = ac.client_id
left join filtered_visits fv on gc.client_id = fv.client_id
where gc.membership_type = 'Premium';



 
